c_stdlib_version:          # [osx and x86]
  - '10.12'                # [osx and x86]
channel_sources:
- conda-forge/label/rust_dev,conda-forge
c_compiler:
  - clang  # [win]
c_compiler_version:
  - 17  # [win]
