{% set name = "polars-ds" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_ds-{{ version }}.tar.gz
  sha256: 8d034c3cfe3ac4502469956f3d053fee0996069170530de34a88aceacbd4449c

build:
  skip: true  # [py<38]
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    # there is no cross-python for linux-64 -> win-64
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not target_platform == "win-64"]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.1,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
    - cargo-feature
  host:
    # this is a hacky way to do cross-compilation from linux to windows
    - python              # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - maturin >=1.2,<2.0  # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - pip                 # [not (build_platform == "linux-64" and target_platform == "win-64")]
  run:
    - python
    - polars >=0.20.6

test:
  imports:
    - polars_ds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abstractqqq/polars_ds_extension
  doc_url: https://polars-ds-extension.readthedocs.io/
  summary: Polars extension for general data science use cases
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
    - xhochy
