{% set name = "polars-ds" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polars_ds-{{ version }}.tar.gz
  sha256: b9114c2c14f28346ceb92405628f884cfb53e636d84715593df938d61b375243

build:
  skip: true  # [py<39]
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    # there is no cross-python for linux-64 -> win-64
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not target_platform == "win-64"]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.1,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}      # [not (build_platform != target_platform and target_platform == "win-64")]
    - {{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
    - cargo-feature
  host:
    # this is a hacky way to do cross-compilation from linux to windows
    - python                # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - maturin >=1.7.4,<2.0  # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - pip                   # [not (build_platform == "linux-64" and target_platform == "win-64")]
  run:
    - python
    - polars >=1.4
    - typing-extensions  # [py<=311]

test:
  imports:
    - polars_ds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abstractqqq/polars_ds_extension
  doc_url: https://polars-ds-extension.readthedocs.io/
  summary: Polars extension for general data science use cases
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - abstractqqq
    - thewchan
    - xhochy
