{% set name = "polars-ds" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_ds-{{ version }}.tar.gz
  sha256: 167f29db7b498083fc8c3ac4855bd1bef7711843cd921cb048026bf5d603e729

build:
  skip: True  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }} 1.77
    - make
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
  run:
    - python
    - polars >=0.20.6
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - polars_ds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abstractqqq/polars_ds_extension
  doc_url: https://polars-ds-extension.readthedocs.io/
  summary: Polars extension for general data science use cases 
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
    - xhochy
